Add Viewport (Room drag and drop)
jankuss/shroom pull request #11
Opened 2020-12-09 14:02 UTC by mtwzim

Viewport created to comply with the needs of issue #10 .

To use the room camera:
```
const room = Room.create(/* ... */);

app.stage.addChild(new RoomCamera(room));
```

Setting drag options:
```
const room = Room.create(/* ... */);

app.stage.addChild(new RoomCamera(room, /* ... */));
```

And using plugins:
```
const room = Room.create(/* ... */);

app.stage.addChild(new RoomCamera(room).pluginName1().pluginName2()); // You can use none, one or all the plugins
```

Plugins available:

- drag **(actived by default)**
- bounce
- clamp
- clampZoom
- decelerate
- follow
- mouseEdges
- pinch
- snap
- snapZoom
- wheel

2020-12-09 17:15 UTC, jankuss requested changes
Is it possible to disable scrolling behavior of that plugin?
When I scroll I don't want the camera to move.

Apart from that, is it necessary to expose all of the api of the Viewport plugin?
I think we should use the features we need internally in the `RoomCamera` class. And that's mostly just dragging and dropping and snapping back when the room is out of bounds.

2020-12-09 17:15 UTC, jankuss commented on src/objects/room/RoomCamera.ts
> +    this.addChild(this.viewport);
Avoid unnecessary comments. The code here speaks for it self.

2020-12-09 17:29 UTC, mtwzim commented on example/src/index.ejs
> +</html>
How do you manage formatting? who formatted the file was the https://prettier.io/

2020-12-09 20:23 UTC, jankuss commented on example/src/index.ejs
> +</html>
I added a `.prettierrc` into master, so everybody has the same formatter.

2020-12-10 01:09 UTC, mtwzim commented on example/src/index.ts
> +} from "../../src/index";
Of course, sorry I was careless and I didn't know about the npm link, I didn't use it.

2020-12-10 01:11 UTC, mtwzim reviewed
Thanks for the code review :)

2020-12-13 20:28 UTC, mtwzim reviewed
Solved

2020-12-13 20:37 UTC, mtwzim reviewed
Resolving this code review

2020-12-15 02:57 UTC, merged